- name: "{{ item }}: Create directory"
  become: true
  file:
    dest: "/etc/pki/{{ item }}"
    state: directory

- name: "{{ item }}: Generate certificate key"
  become: true
  community.crypto.openssl_privatekey:
    path: "/etc/pki/{{ item }}/private.pem"

- name: "{{ item }}: Generate CSR"
  become: true
  community.crypto.openssl_csr:
    path: "/etc/pki/{{ item }}/private.csr"
    privatekey_path: "/etc/pki/{{ item }}/private.pem"
    common_name: "{{ item }}"
    subject_alt_name:
        - "DNS:*.{{ item }}"
        - "DNS:{{ item }}"

- name: "{{ item }}: Create a challenge"
  become: true
  community.crypto.acme_certificate:
    account_key_src: "/etc/pki/acme.pem"
    account_email: "{{ acme_email }}"
    src: "/etc/pki/{{ item }}/private.csr"
    cert: "/etc/pki/{{ item }}/private.crt"
    challenge: dns-01
    # acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
    acme_directory: https://acme-v02.api.letsencrypt.org/directory
    acme_version: 2
    remaining_days: 30
    terms_agreed: yes
  register: acme_data

- name: Set challenges variable
  ansible.builtin.set_fact:
    challenge_data_filtered: "{{ acme_data.challenge_data_dns | default({}) | dict2items | subelements('value') }}"

- name: "{{ item }}: Create TXT record"
  community.general.cloudflare_dns:
    zone: "{{ item }}"
    account_email: "{{ dns_cloudflare_email }}"
    api_token: "{{ dns_cloudflare_api_token }}"
    type: TXT
    record: "{{ challenge.0.key }}"
    value: "{{ challenge.1 }}"
    ttl: 1
    state: present
  loop: "{{ challenge_data_filtered }}"
  loop_control:
    loop_var: challenge
  when: acme_data is changed

- name: "{{ item }}: Validated and retrieve the certs"
  become: true
  community.crypto.acme_certificate:
    account_key_src: "/etc/pki/acme.pem"
    account_email: "{{ acme_email }}"
    src: "/etc/pki/{{ item }}/private.csr"
    cert: "/etc/pki/{{ item }}/private.crt"
    fullchain: "/etc/pki/{{ item }}/fullchain.crt"
    chain: "/etc/pki/{{ item }}/intermediate.crt"
    challenge: dns-01
    # acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
    acme_directory: https://acme-v02.api.letsencrypt.org/directory
    acme_version: 2
    remaining_days: 30
    terms_agreed: yes
    data: "{{ acme_data }}"
  when: acme_data is changed

- name: "{{ item }}: Remove TXT records"
  delegate_to: localhost
  community.general.cloudflare_dns:
    zone: "{{ item }}"
    account_email: "{{ dns_cloudflare_email }}"
    api_token: "{{ dns_cloudflare_api_token }}"
    type: TXT
    record: "{{ challenge.0.key }}"
    ttl: 60
    state: absent
  loop: "{{ challenge_data_filtered }}"
  loop_control:
    loop_var: challenge
  when: acme_data is changed

- name: Reload nginx
  become: true
  service:
    name: nginx
    state: reloaded
    enabled: yes
  when: acme_data is changed
