confdir /etc/chrony/conf.d

{% if chrony_servers is defined %}
{% for server in chrony_servers %}
server {{ server }}
{% endfor %}
{% endif %}

{% if chrony_pools is defined %}
{% for pool in chrony_pools %}
pool {{ pool }}
{% endfor %}
{% endif %}

{% if chrony_allows is defined %}
{% for allow in chrony_allows %}
allow {{ allow }}
{% endfor %}
{% endif %}

sourcedir /run/chrony-dhcp
sourcedir /etc/chrony/sources.d
keyfile /etc/chrony/chrony.keys
driftfile /var/lib/chrony/chrony.drift
ntsdumpdir /var/lib/chrony
logdir /var/log/chrony
maxupdateskew 100.0
rtcsync
makestep 1 3
leapsectz right/UTC
