- name: Install X.org
  become: yes
  package:
    name:
      - ttf-terminus-nerd
      - ttf-hack-nerd
      - noto-fonts
      - ttf-jetbrains-mono
      - noto-fonts-cjk
      - noto-fonts-emoji
      - noto-fonts-extra
      - otf-fira-mono
      - otf-fira-sans
      - terminus-font
      - ttf-caladea
      - ttf-carlito
      - ttf-croscore
      - ttf-dejavu
      - ttf-droid
      - ttf-fira-code
      - ttf-hack
      - ttf-inconsolata
      - ttf-liberation
      - ttf-nerd-fonts-symbols-common
      - ttf-ubuntu-font-family
      - v4l2loopback-dkms
      - v4l2loopback-utils
      - xclip
      - xorg
      - xdg-desktop-portal

