---
llamacpp_container_name: llama
llamacpp_container_dir: "/home/{{ admin_user }}/containers/{{ llamacpp_container_name }}"

llamacpp:
  image: ghcr.io/ggml-org/llama.cpp:server
  port: 3110
  mem_limit: 512
  ctx_size: 49152
  n_parallel: 3
  threads: 4
  n_predict: 1024
  cache_type:
    k: q4_0
    v: q4_0
  model:
    filename: Qwen3-4B-Q4_K_M.gguf
