---
- name: Install logrotate
  ansible.builtin.package:
    name: logrotate
    state: present

- name: Render config
  ansible.builtin.template:
    src: logrotate.j2
    dest: "/etc/logrotate.d/{{ item.name }}"
    mode: "0644"
  loop: "{{ entries }}"
  when:
    - entries is defined
