---
- name: Ensure container project directory exists
  file:
    path: "{{ shizoidgo_container_dir }}"
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: "0755"

- name: Generate config.yaml
  copy:
    content: "{{ shizoidgo | to_nice_yaml }}"
    dest: "{{ shizoidgo_container_dir }}/config.yaml"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: "0644"
  register: shizoidgo_config

- name: Run container
  include_role:
    name: podman
    tasks_from: container.yaml
  vars:
    container_name: "{{ shizoidgo_container_name }}"
    podman_compose_dest: "{{ shizoidgo_container_dir }}/compose.yaml"
    compose_project_dir: "{{ shizoidgo_container_dir }}"
    podman_recreate: "{{ shizoidgo_config is changed }}"
