- name: Install drivers
  become: yes
  package:
    name:
      - nvidia
      - lib32-nvidia-utils
      - nvidia-settings
      - nvidia-utils
    state: present

# - name: Early KMS start modules
#   become: yes
#   lineinfile:
#     dest: /etc/mkinitcpio.conf
#     regexp: '^MODULES=('
#     line: 'MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)'

- name: Create initial ramdisk
  become: yes
  command: /usr/bin/mkinitcpio -P
