---
- name: Ensure container project directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: "0755"
  loop:
    - "{{ valkey_container_dir }}"
    - "{{ valkey_container_dir }}/conf"

- name: Deploy Valkey config
  template:
    src: valkey.conf.j2
    dest: "{{ valkey_container_dir }}/conf/valkey.conf"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: "0644"
  register: valkey_config

- name: Run container
  include_role:
    name: podman
    tasks_from: container.yaml
  vars:
    container_name: "{{ valkey_container_name }}"
    podman_compose_dest: "{{ valkey_container_dir }}/compose.yaml"
    compose_project_dir: "{{ valkey_container_dir }}"
    podman_recreate: "{{ valkey_config is changed }}"
