---
- name: Ensure esphome project directory exists
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: "0755"
  loop:
    - "{{ esphome_container_dir }}"
    - "{{ esphome_container_dir }}/config"

- name: Run container
  include_role:
    name: podman
    tasks_from: container.yaml
  vars:
    container_name: "{{ esphome_container_name }}"
