- name: Checkout sources
  become: true
  git:
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: "/opt/asdf-vm"
    single_branch: yes
    version: "{{ asdf.version }}"

- name: Install dev packages
  become: true
  apt:
    state: latest
    update_cache: yes
    autoremove: yes
    purge: yes
    name:
      - build-essential
      - libssl-dev
      - zlib1g-dev
