---
- name: Install Alpine-specific packages for rootless podman
  become: true
  package:
    state: present
    update_cache: yes
    name:
      - shadow-subids

- name: Enable cgroups v2
  become: true
  copy:
    dest: /etc/conf.d/cgroups
    content: rc_cgroup_mode="unified"
    mode: "0644"

- name: Enable and start cgroups service
  become: true
  service:
    name: cgroups
    state: started
    enabled: yes
