---
- name: Ensure OpenRC service script is installed
  become: true
  template:
    src: "templates/openrc-podman-compose.initd.j2"
    dest: "/etc/init.d/{{ container_name }}"
    owner: root
    group: root
    mode: "0755"

- name: Enable and start OpenRC service
  become: true
  ansible.builtin.service:
    name: "{{ container_name }}"
    enabled: true
    state: started

- name: Apply changes to compose project
  become: true
  ansible.builtin.command: "service {{ container_name }} reload"
  when: podman_apply | default(false) | bool
  changed_when: true
