---
- name: Ensure OpenRC service script is installed
  become: true
  template:
    src: "templates/openrc-podman-compose.initd.j2"
    dest: "/etc/init.d/{{ container_name }}"
    owner: root
    group: root
    mode: "0755"

- name: Enable OpenRC service at boot
  become: true
  command: "rc-update add {{ container_name }} default"
  register: openrc_enable
  changed_when: "'added to runlevel' in (openrc_enable.stdout | default(''))"

- name: Reload compose project
  become: true
  command: "service {{ container_name }} reload"
