# intel-media-driver
# vulkan-intel
# vulkan-mesa-layers
#TODO: Debian config

- name: Early KMS start
  become: yes
  lineinfile:
    dest: /etc/mkinitcpio.conf
    regexp: '^MODULES=('
    line: 'MODULES=(i915)'
