#TODO: Debian config

- name: Install drivers
  become: true
  package:
    name:
      - intel-media-driver
      - lib32-vulkan-icd-loader
      - libva-intel-driver
      - vulkan-icd-loader
      - vulkan-intel
      - vulkan-tools
    state: present

- name: Early KMS start
  become: true
  lineinfile:
    dest: /etc/mkinitcpio.conf
    regexp: "^MODULES="
    line: "MODULES=(i915)"
