- name: Install Chrony
  become: true
  package:
    state: latest
    name: chrony
    update_cache: yes

- name: Configure Chrony
  become: true
  copy:
    src: chrony.conf
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: 644
  notify: Restart Chrony

- name: Enable chronyd
  become: true
  service:
    name: chronyd
    enabled: true
