- name: Install Chrony
  become: true
  package:
    state: latest
    name: chrony
    update_cache: yes

- name: Configure Chrony
  become: true
  copy:
    src: chrony.conf
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Restart chronyd
  become: true
  service:
    name: chronyd
    state: restarted
