- name: Install tmux
  include_role:
    name: yay
  vars:
    packages:
      - tmux

- name: Create plugins directories
  file:
    path: "/home/{{ admin_user }}/.config/tmux/plugins/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - catppuccin

- name: Install catppuccin theme
  git:
    repo: "https://github.com/catppuccin/tmux.git"
    dest: "/home/{{ admin_user }}/.config/tmux/plugins/catppuccin/tmux"
    single_branch: yes
    update: yes
    version: "v2.1.3"

- name: Copy unit file
  become: true
  copy:
    src: tmux.service
    dest: /etc/systemd/system/tmux@.service

- name: Copy config file
  template:
    src: .tmux.conf
    dest: ~/.tmux.conf

- name: Enable and start service
  become: true
  systemd:
    name: "tmux@{{ admin_user }}"
    enabled: true
    # state: started
    daemon_reload: true
