- name: Install packages
  become: true
  ansible.builtin.package:
    state: present
    name:
      - tmux

- name: Create plugins directories
  ansible.builtin.file:
    path: "/home/{{ admin_user }}/.config/tmux/plugins/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - catppuccin

- name: Install catppuccin theme
  ansible.builtin.git:
    repo: "https://github.com/catppuccin/tmux.git"
    dest: "/home/{{ admin_user }}/.config/tmux/plugins/catppuccin/tmux"
    single_branch: true
    update: true
    version: "v2.3"

- name: Copy unit file
  become: true
  ansible.builtin.copy:
    src: tmux.service
    dest: /etc/systemd/system/tmux@.service

- name: Copy config file
  ansible.builtin.template:
    src: .tmux.conf
    dest: ~/.tmux.conf

- name: Enable and start service
  become: true
  ansible.builtin.systemd:
    name: "tmux@{{ admin_user }}"
    enabled: true
    # state: started
    daemon_reload: true
