FROM docker.io/library/golang:1.26-alpine3.22 AS build
WORKDIR /app
COPY . .
RUN go mod download \
  && go build -trimpath -ldflags='-s -w' -o olcrtc ./cmd/olcrtc

FROM docker.io/library/alpine:3.22
RUN apk add --no-cache ffmpeg ca-certificates
WORKDIR /app
COPY --from=build /app/olcrtc /app/olcrtc
COPY --from=build /app/data /app/data
ENTRYPOINT ["/app/olcrtc"]
CMD ["config.yaml"]
