- name: Install Sway
  include_role:
    name: yay
  vars:
    packages:
      - sway
      - wl-clipboard
      - swaylock
      - swayidle

- name: Create directory
  become: true
  file:
    path: /etc/sway/config.d
    state: directory

- name: Creating root config
  become: true
  copy:
    src: config
    dest: /etc/sway/config
