---
- name: Update apk index
  become: true
  package:
    update_cache: yes

- name: Upgrade apk-tools after repository change
  become: true
  package:
    name: apk-tools
    state: latest
  when: alpine_repositories.changed

- name: Upgrade the system
  become: true
  environment:
    LC_ALL: C
  ansible.builtin.command: >-
    apk upgrade {{ '--available' if alpine_repositories.changed else '' }}
  register: apk_upgrade
  changed_when: "'Upgrading' in apk_upgrade.stdout or 'Installing' in apk_upgrade.stdout"

- name: Reset connection after system upgrade
  meta: reset_connection

- name: Rediscover Python interpreter
  setup:
    gather_subset: "!all,min"
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Update Python interpreter fact
  set_fact:
    ansible_python_interpreter: "{{ ansible_facts.discovered_interpreter_python }}"

- name: Remove motd
  become: true
  file:
    path: "/etc/motd"
    state: absent

- name: Install packages
  become: true
  package:
    state: present
    name:
      - ca-certificates
      - openssh
      - openssh-client
      - p7zip
      - tzdata

- name: Update user
  become: true
  ignore_errors: true
  user:
    name: "{{ admin_user }}"
    shell: "/bin/zsh"
    system: yes
    create_home: yes
    expires: -1
    append: yes
    groups:
      - audio
      - input
      - netdev
      - video
      - wheel

- name: Enable passwordless sudo
  become: true
  ignore_errors: true
  lineinfile:
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    state: present
    path: "/etc/sudoers"
