- name: Configure pacman options
  become: true
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    marker: "# {mark} ANSIBLE MANAGED OPTIONS"
    insertafter: '^\[options\]'
    block: |
      ILoveCandy
      Color
      ParallelDownloads = 5
      CleanMethod = KeepInstalled

- name: Check whether multilib is already enabled
  become: true
  ansible.builtin.command: grep -c '^\[multilib\]' /etc/pacman.conf
  register: pacman_multilib
  changed_when: false
  failed_when: false

- name: Enable multilib
  become: true
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    marker: "# {mark} ANSIBLE MANAGED MULTILIB"
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist
  when: pacman_multilib.stdout | int == 0

- name: Upgrade system
  become: true
  environment:
    LC_ALL: C
  ansible.builtin.command: pacman -Syu --noconfirm
  register: pacman_upgrade
  changed_when: "'there is nothing to do' not in pacman_upgrade.stdout"

- name: Install packages
  become: true
  ansible.builtin.package:
    state: present
    name:
      - base-devel
      - cdrtools
      - curl
      - diffutils
      - fd
      - gnupg
      - go
      - gzip
      - mc
      - net-tools
      - networkmanager
      - nfs-utils
      - openssh
      - p7zip
      - sudo
      - tar
      - terminus-font
      - unrar
      - unzip
      - usbutils
      - wget

- name: Enable NetworkManager service
  become: true
  ansible.builtin.service:
    name: NetworkManager
    enabled: true
    state: started

- name: Update user
  become: true
  ansible.builtin.user:
    name: "{{ admin_user }}"
    shell: "/bin/zsh"
    system: true
    create_home: true
    expires: -1
    append: true
    groups:
      - adm
      - audio
      - floppy
      - games
      - input
      - kvm
      - lock
      - log
      - mail
      - mem
      - network
      - optical
      - power
      - render
      - rfkill
      - scanner
      - storage
      - systemd-journal
      - tty
      - users
      - uucp
      - video
      - wheel

- name: Enable passwordless sudo
  become: true
  ansible.builtin.lineinfile:
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    state: present
    path: "/etc/sudoers"
    validate: "/usr/sbin/visudo -cf %s"

- name: Run distribution specific tasks
  ansible.builtin.include_tasks: "yay.yaml"
