---
- name: Disable all apt recommendations and suggestions
  become: true
  copy:
    dest: /etc/apt/apt.conf.d/99local
    content: |-
      APT::Install-Recommends "0";
      APT::Install-Suggests "0";
    owner: root
    group: root
    mode: 644

- name: Install packages
  become: true
  package:
    state: latest
    autoremove: yes
    purge: yes
    name:
      - apt-transport-https
      - gnupg2
      - openssh-client
      - p7zip-full

- name: Update user
  become: true
  ignore_errors: true
  user:
    name: "{{ admin_user }}"
    shell: "/bin/zsh"
    system: yes
    create_home: yes
    expires: -1
    append: yes
    groups:
      - adm
      - games
      - sudo
      - tty

- name: Enable passwordless sudo
  become: true
  ignore_errors: true
  lineinfile:
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    state: present
    path: "/etc/sudoers"
