- name: Install common packages and update databases
  become: true
  package:
    state: latest
    update_cache: yes
    name:
      - ca-certificates
      - curl
      - fzf
      - git
      - neovim
      - starship
      - sudo
      - wget
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting

- name: Run distribution specific tasks
  include_tasks: "{{ ansible_os_family }}.yaml"

- name: Disable SSH password authentication
  become: true
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: '^(\#|\s)*PasswordAuthentication\s*(yes|no)$'
    line: "PasswordAuthentication no"
    validate: "/usr/sbin/sshd -t -f %s"
  notify: Reload sshd

- name: Set SSH port
  become: true
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: '^(\#|\s)*Port\s*\d+$'
    line: "Port {{ ansible_port }}"
    validate: "/usr/sbin/sshd -t -f %s"
  notify: Reload sshd

- name: Set hostname in /etc/hostname
  become: true
  copy:
    content: "{{ hostname|default(inventory_hostname) }}\n"
    dest: "/etc/hostname"

- name: Set hostname in /etc/hosts
  become: true
  lineinfile:
    regexp: "^127.0.1.1"
    line: "127.0.1.1 {{ hostname|default(inventory_hostname) }}.localdomain {{
      hostname|default(inventory_hostname) }}"
    state: present
    path: "/etc/hosts"

- name: Minimize swappines
  become: true
  copy:
    content: "vm.swappiness = 1\n"
    dest: "/etc/sysctl.d/swappiness.conf"

- name: Disable PC speaker
  become: true
  copy:
    content: "blacklist pcspkr

      blacklist snd_pcsp\n"
    dest: "/etc/modprobe.d/nobeep.conf"

- name: Create timezone symbolic link
  become: true
  file:
    src: "/usr/share/zoneinfo/{{ TIMEZONE }}"
    dest: "/etc/localtime"
    state: link

- name: Create udev directory
  become: true
  file:
    path: "/etc/udev/rules.d"
    state: directory
    mode: "0755"
  when: ansible_facts['os_family'] != 'Alpine'

- name: Set keymap via udev
  become: true
  template:
    src: "templates/75-x11-input.rules.j2"
    dest: "/etc/udev/rules.d/75-x11-input.rules"
  when: ansible_facts['os_family'] != 'Alpine'

- name: Copy locale.conf
  become: true
  template:
    src: "templates/locale.conf.j2"
    dest: "/etc/locale.conf"

- name: Ensure the locales exists
  become: true
  locale_gen:
    name:
      - en_US.UTF-8
      - ru_RU.UTF-8
    state: present
  when: ansible_facts['os_family'] != 'Alpine'

- name: Set timezone
  become: true
  timezone:
    name: "{{ TIMEZONE }}"
    hwclock: UTC

- name: Generate locale
  become: true
  locale_gen:
    name: "{{ LC_ALL }}"
  when: ansible_facts['os_family'] != 'Alpine'

- name: Ensure .profile exists
  copy:
    content: ""
    dest: /home/{{ admin_user }}/.profile
    force: false

- name: Define export EDITOR
  lineinfile:
    state: present
    path: /home/{{ admin_user }}/.profile
    regexp: "^export EDITOR="
    line: "export EDITOR=nvim"

- name: Create directory
  file:
    path: "/home/{{ admin_user }}/.ssh"
    state: directory
    mode: "0700"

- name: Add public key
  lineinfile:
    state: present
    path: /home/{{ admin_user }}/.ssh/authorized_keys
    line: "{{ admin_public_key }}"

- name: Define key bindings
  lineinfile:
    state: present
    path: /home/{{ admin_user }}/.profile
    line: "bindkey '{{ item.key }}' {{ item.command }}"
  loop:
    - { key: "^H", command: "backward-kill-word" }
    - { key: "^[[H", command: "beginning-of-line" }
    - { key: "^[OH", command: "beginning-of-line" }
    - { key: "^[[F", command: "end-of-line" }
    - { key: "^[OF", command: "end-of-line" }
    - { key: "^[[3~", command: "delete-char" }
    - { key: "^[[5~", command: "up-line-or-history" }
    - { key: "^[[6~", command: "down-line-or-history" }
    - { key: "^[[A", command: "up-line-or-beginning-search" }
    - { key: "^[OA", command: "up-line-or-beginning-search" }
    - { key: "^[[B", command: "down-line-or-beginning-search" }
    - { key: "^[OB", command: "down-line-or-beginning-search" }
    - { key: "^[[Z", command: "reverse-menu-complete" }
    - { key: "^[[2;5~", command: "copy-region-as-kill" }
    - { key: "^[[3;5~", command: "kill-word" }
    - { key: "^[[1;5C", command: "forward-word" }
    - { key: "^[[1;5D", command: "backward-word" }

- name: Set home permissions
  file:
    path: "/home/{{ admin_user }}"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: "700"

- name: Create wakatime config
  template:
    dest: "/home/{{ admin_user }}/.wakatime.cfg"
    src: ".wakatime.cfg.j2"
  when:
    - wakatime is defined
    - wakatime.key is defined

- name: Clone oh my zsh sources
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    dest: "/home/{{ admin_user }}/.oh-my-zsh"
    single_branch: yes
    depth: 1
    update: yes

- name: Set permissions of oh-my-zsh
  become: true
  file:
    path: "/home/{{ admin_user }}/.oh-my-zsh"
    mode: "go-w"

- name: Creating .zshrc
  template:
    src: templates/.zshrc.j2
    dest: /home/{{ admin_user }}/.zshrc

- name: Create config directory
  file:
    path: "/home/{{ admin_user }}/.config"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    state: directory

- name: Copy starship config
  template:
    src: starship.toml.j2
    dest: /home/{{ admin_user }}/.config/starship.toml
