- name: Check if yay available
  ansible.builtin.stat:
    path: /usr/bin/yay
  register: yay_binary

- name: Install build dependencies
  become: true
  ansible.builtin.package:
    name:
      - fakeroot
      - git
      - base-devel
    state: present
    update_cache: true
  when: not yay_binary.stat.exists

- name: Checkout sources
  become: true
  become_user: "{{ admin_user }}"
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "/home/{{ admin_user }}/yay"
  when: not yay_binary.stat.exists

- name: Build and install yay
  become: true
  become_user: "{{ admin_user }}"
  ansible.builtin.command:
    cmd: makepkg -si --noconfirm
    chdir: "/home/{{ admin_user }}/yay"
  when: not yay_binary.stat.exists

- name: Remove sources
  ansible.builtin.file:
    state: absent
    path: "/home/{{ admin_user }}/yay"
  when: not yay_binary.stat.exists

- name: Show packages
  ansible.builtin.debug:
    msg: "{{ packages }}"
  when: packages is defined

- name: Install batch of packages
  become: true
  become_user: "{{ admin_user }}"
  ansible.builtin.command: >-
    yay -S
      --answerclean none --answeredit none --answerupgrade none --answerdiff none
      --removemake --noconfirm --combinedupgrade --needed
      {{ packages | map('quote') | join(' ') }}
  environment:
    LC_ALL: C
  register: yay_install
  changed_when: "'there is nothing to do' not in yay_install.stdout"
  when: packages is defined
