- name: Install alacritty
  become: true
  package:
    state: latest
    name:
      - alacritty
      - nerd-fonts
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - noto-fonts-extra
      - otf-fira-mono
      - otf-fira-sans
      - ttf-caladea
      - ttf-carlito
      - ttf-croscore
      - ttf-fira-code
      - ttf-inconsolata
      - ttf-liberation
      - ttf-ubuntu-font-family

- name: Copy config file
  template:
    src: .alacritty.toml.j2
    dest: ~/.alacritty.toml
