- name: Install packages
  become: true
  apt:
    force_apt_get: yes
    state: latest
    update_cache: yes
    autoremove: yes
    purge: yes
    name:
      - nfs-common
      - nfs-kernel-server

- name: Create network files
  become: true
  template:
    src: exports.j2
    dest: /etc/exports
    mode: 0644
