- name: Install latest NeoVim
  become: true
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    dest: /opt/nvim.appimage

- name: Create a symbolic link
  become: true
  file:
    src: /opt/nvim.appimage
    dest: /usr/bin/nvim
    state: link

- name: Use Light configuration
  lineinfile:
    state: present
    path: /home/{{ admin_user }}/.profile
    line: "export LIGHT_NVIM=true"
