---
- name: Ensure pihole project directory exists
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: "0755"
  loop:
    - "{{ pihole_container_dir }}"
    - "{{ pihole_container_dir }}/etc-pihole"
    - "{{ pihole_container_dir }}/etc-dnsmasq.d"

- name: Run container
  include_role:
    name: podman
    tasks_from: container.yaml
  vars:
    container_name: "{{ pihole_container_name }}"

- name: Configure Pi-hole blocklists
  ansible.builtin.include_tasks: lists.yaml
  when: pihole.lists is defined and pihole.lists | length > 0
